### PR TITLE
Add support for GHC 9.12

### LINKED ISSUE #122: Support GHC-9.12
Currently this library fails to build with GHC-9.12 with the following errors:
<details><summary>Details</summary>
<p>

```
Building library for ghc-source-gen-0.4.5.0..
[ 1 of 18] Compiling GHC.SourceGen.Pretty ( src/GHC/SourceGen/Pretty.hs, dist/build/GHC/SourceGen/Pretty.o, dist/build/GHC/SourceGen/Pretty.dyn_o )
[ 2 of 18] Compiling GHC.SourceGen.Syntax.Internal ( src/GHC/SourceGen/Syntax/Internal.hs, dist/build/GHC/SourceGen/Syntax/Internal.o, dist/build/GHC/SourceGen/Syntax/Internal.dyn_o )
[ 3 of 18] Compiling GHC.SourceGen.Name.Internal ( src/GHC/SourceGen/Name/Internal.hs, dist/build/GHC/SourceGen/Name/Internal.o, dist/build/GHC/SourceGen/Name/Internal.dyn_o )
[ 4 of 18] Compiling GHC.SourceGen.Name ( src/GHC/SourceGen/Name.hs, dist/build/GHC/SourceGen/Name.o, dist/build/GHC/SourceGen/Name.dyn_o )
[ 5 of 18] Compiling GHC.SourceGen.Lit.Internal ( src/GHC/SourceGen/Lit/Internal.hs, dist/build/GHC/SourceGen/Lit/Internal.o, dist/build/GHC/SourceGen/Lit/Internal.dyn_o )
[ 6 of 18] Compiling GHC.SourceGen.Pat.Internal ( src/GHC/SourceGen/Pat/Internal.hs, dist/build/GHC/SourceGen/Pat/Internal.o, dist/build/GHC/SourceGen/Pat/Internal.dyn_o )
[ 7 of 18] Compiling GHC.SourceGen.Module ( src/GHC/SourceGen/Module.hs, dist/build/GHC/SourceGen/Module.o, dist/build/GHC/SourceGen/Module.dyn_o )
src/GHC/SourceGen/Module.hs:50:60: error: [GHC-61689]
    Module ‘GHC.Hs’ does not export ‘AnnKeywordId’.
   |
50 |     , hsmodDeprecMessage, hsmodHaddockModHeader, hsmodAnn, AnnKeywordId, XModulePs (XModulePs, hsmodLayout), noAnn, GhcPs, XImportDeclPass (XImportDeclPass, ideclAnn), SrcSpanAnnA, noExtField
   |                                                            ^^^^^^^^^^^^
[ 8 of 18] Compiling GHC.SourceGen.Lit ( src/GHC/SourceGen/Lit.hs, dist/build/GHC/SourceGen/Lit.o, dist/build/GHC/SourceGen/Lit.dyn_o )
src/GHC/SourceGen/Lit.hs:54:28: error: [GHC-83865]
    • Couldn't match type: [a0]
                     with: GHC.Parser.Annotation.EpToken "-"
      Expected: Language.Haskell.Syntax.Extension.XNPat
                  GHC.Hs.Extension.GhcPs
        Actual: [a0]
    • In the first argument of ‘NPat’, namely ‘[]’
      In the second argument of ‘($)’, namely
        ‘NPat [] (mkLocated l) Nothing noSyntaxExpr’
      In the expression:
        withPlaceHolder $ NPat [] (mkLocated l) Nothing noSyntaxExpr
   |
54 |                     $ NPat [] (mkLocated l) Nothing noSyntaxExpr
   |                            ^^
[ 9 of 18] Compiling GHC.SourceGen.Expr.Internal ( src/GHC/SourceGen/Expr/Internal.hs, dist/build/GHC/SourceGen/Expr/Internal.o, dist/build/GHC/SourceGen/Expr/Internal.dyn_o )
[10 of 18] Compiling GHC.SourceGen.Binds.Internal ( src/GHC/SourceGen/Binds/Internal.hs, dist/build/GHC/SourceGen/Binds/Internal.o, dist/build/GHC/SourceGen/Binds/Internal.dyn_o )
src/GHC/SourceGen/Binds/Internal.hs:54:28: error: [GHC-83865]
    • Couldn't match type: [GHC.Types.SrcLoc.GenLocated
                              GHC.Parser.Annotation.SrcSpanAnnA
                              (HsBindLR GHC.Hs.Extension.GhcPs GHC.Hs.Extension.GhcPs)]
                     with: GHC.Data.Bag.Bag
                             (GHC.Types.SrcLoc.GenLocated (SrcSpanAnn ann0) HsBind')
      Expected: GHC.Parser.Annotation.AnnSortKey
                  GHC.Parser.Annotation.BindTag
                -> GHC.Data.Bag.Bag
                     (GHC.Types.SrcLoc.GenLocated (SrcSpanAnn ann0) HsBind')
                -> [GHC.Types.SrcLoc.GenLocated
                      (SrcSpanAnn GHC.Parser.Annotation.AnnListItem) Sig']
                -> HsValBindsLR GHC.Hs.Extension.GhcPs GHC.Hs.Extension.GhcPs
        Actual: Language.Haskell.Syntax.Extension.XValBinds
                  GHC.Hs.Extension.GhcPs GHC.Hs.Extension.GhcPs
                -> LHsBindsLR GHC.Hs.Extension.GhcPs GHC.Hs.Extension.GhcPs
                -> [LSig GHC.Hs.Extension.GhcPs]
                -> HsValBindsLR GHC.Hs.Extension.GhcPs GHC.Hs.Extension.GhcPs
    • In the first argument of ‘withNoAnnSortKey’, namely ‘ValBinds’
      In the second argument of ‘($)’, namely
        ‘withNoAnnSortKey
           ValBinds (listToBag $ map mkLocated binds) (map mkLocated sigs)’
      In the expression:
        HsValBinds noAnn
          $ withNoAnnSortKey
              ValBinds (listToBag $ map mkLocated binds) (map mkLocated sigs)
   |
54 |         $ withNoAnnSortKey ValBinds
   |                            ^^^^^^^^
src/GHC/SourceGen/Binds/Internal.hs:124:23: error: [GHC-83865]
    • Couldn't match type ‘[a0]’
                     with ‘Language.Haskell.Syntax.Extension.NoExtField’
      Expected: Language.Haskell.Syntax.Extension.XCMatch
                  GHC.Hs.Extension.GhcPs LHsExpr'
        Actual: [a0]
    • In the first argument of ‘Match’, namely ‘[]’
      In the expression:
        Match
          [] context (map builtPat $ map parenthesize $ rawMatchPats r)
          (mkGRHSs $ rawMatchGRHSs r)
      In an equation for ‘mkMatch’:
          mkMatch r
            = Match
                [] context (map builtPat $ map parenthesize $ rawMatchPats r)
                (mkGRHSs $ rawMatchGRHSs r)
    |
124 |     mkMatch r = Match [] context
    |                       ^^
src/GHC/SourceGen/Binds/Internal.hs:125:22: error: [GHC-83865]
    • Couldn't match type: [GHC.Types.SrcLoc.GenLocated
                              GHC.Parser.Annotation.SrcSpanAnnA
                              (Language.Haskell.Syntax.Pat.Pat GHC.Hs.Extension.GhcPs)]
                     with: GHC.Types.SrcLoc.GenLocated
                             GHC.Parser.Annotation.EpaLocation
                             [GHC.Types.SrcLoc.GenLocated
                                GHC.Parser.Annotation.SrcSpanAnnA
                                (Language.Haskell.Syntax.Pat.Pat GHC.Hs.Extension.GhcPs)]
      Expected: Language.Haskell.Syntax.Extension.XRec
                  GHC.Hs.Extension.GhcPs
                  [Language.Haskell.Syntax.Pat.LPat GHC.Hs.Extension.GhcPs]
        Actual: [GHC.Types.SrcLoc.GenLocated
                   GHC.Parser.Annotation.SrcSpanAnnA
                   (Language.Haskell.Syntax.Pat.Pat GHC.Hs.Extension.GhcPs)]
    • In the third argument of ‘Match’, namely
        ‘(map builtPat $ map parenthesize $ rawMatchPats r)’
      In the expression:
        Match
          [] context (map builtPat $ map parenthesize $ rawMatchPats r)
          (mkGRHSs $ rawMatchGRHSs r)
      In an equation for ‘mkMatch’:
          mkMatch r
            = Match
                [] context (map builtPat $ map parenthesize $ rawMatchPats r)
                (mkGRHSs $ rawMatchGRHSs r)
    |
125 |                     (map builtPat $ map parenthesize $ rawMatchPats r)
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[11 of 18] Compiling GHC.SourceGen.Type.Internal ( src/GHC/SourceGen/Type/Internal.hs, dist/build/GHC/SourceGen/Type/Internal.o, dist/build/GHC/SourceGen/Type/Internal.dyn_o )
src/GHC/SourceGen/Type/Internal.hs:21:31: error: [GHC-10237]
    In the import of ‘GHC.Parser.Annotation’:
      an item called ‘AnnParen’ is exported, but it does not export any children
      (constructors, class methods or field names) called ‘AnnParen’.
   |
21 | import GHC.Parser.Annotation (AnnParen (AnnParen), ParenType (AnnParens), noAnn, noSpanAnchor)
   |                               ^^^^^^^^^^^^^^^^^^^
src/GHC/SourceGen/Type/Internal.hs:21:52: error: [GHC-61689]
    Module ‘GHC.Parser.Annotation’ does not export ‘ParenType’.
   |
21 | import GHC.Parser.Annotation (AnnParen (AnnParen), ParenType (AnnParens), noAnn, noSpanAnchor)
   |  
```

</p>
</details>

### PR DESCRIPTION
**Pull request by avdv**
Fixes #122

### CODE REVIEW

**Comment by avdv** [comment]
@jinwoo could you perhaps approve the workflow to get this going? :bow:

**Comment by avdv** [comment]
> I'm seeing a lot of CI failures. Could you fix them?

Sure, I'll take a look.
